spring:
  application:
    name: payment-service
  profiles:
    group:
      local: "common, dev, secret-dev"
      prod: "common, prod, secret-prod"
      test: "test, secret-test"
    include: secret
    active: local
---
spring:
  config:
    activate:
      on-profile: common

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 30
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  retry:
    instances:
      confirmPayment:
        maxAttempts: 4  # 최대 3번 재시도
        waitDuration: 500ms  # 재시도 사이의 대기 시간
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
        ignore-exceptions:
          - com.common.web.exception.BusinessException
          - com.fasterxml.jackson.core.JsonProcessingException
        exponentialBackoffMultiplier: 2 # 지수 백오프: 0.5s → 1s → 2s → 4s
        enableRandomizedWait: true

  circuitbreaker:
    instances:
      confirmPayment:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 30s
        minimumNumberOfCalls: 20
        failureRateThreshold: 30
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - com.common.web.exception.BusinessException

logging:
  level:
    com.purchase.preorder.payment_service.api.external.TossPaymentsClient: DEBUG
    com.purchase.preorder.settlement_service.api.external.TossSettlementClient: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8886

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      tossPaymentsClient:
        connect-timeout: 500
        read-timeout: 1200
      nicePaymentsClient:
        connect-timeout: 500
        read-timeout: 1200
      tossSettlementClient:
        connect-timeout: 60000
        read-timeout: 60000
#      niceSettlementClient:
#        connect-timeout: 60000
#        read-timeout: 60000

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8079

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

feign:
  client:
    config:
      tossPaymentsClient:
        connect-timeout: 1000
        read-timeout: 1500
      nicePaymentsClient:
        connect-timeout: 1000
        read-timeout: 1500
      tossSettlementClient:
        connect-timeout: 60000
        read-timeout: 60000
#      niceSettlementClient:
#        connect-timeout: 60000
#        read-timeout: 60000

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
  cloud:
    gateway:
      enabled: false

eureka:
  client:
    enabled: false

feign:
  client:
    config:
      tossPaymentsClient:
        connect-timeout: 1000
        read-timeout: 1500
      nicePaymentsClient:
        connect-timeout: 1000
        read-timeout: 1500
      tossSettlementClient:
        connect-timeout: 60000
        read-timeout: 60000
#      niceSettlementClient:
#        connect-timeout: 60000
#        read-timeout: 60000

resilience4j:
  circuitbreaker:
    instances:
      confirmPayment:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      confirmPayment:
        maxAttempts: 3
        waitDuration: 1s