spring:
  application:
    name: order-service
  profiles:
    group:
      local: "common, dev, secret-dev"
      prod: "common, prod, secret-prod"
      test: "test, secret-test"
    include: secret
    active: local
---
spring:
  config:
    activate:
      on-profile: common

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 30
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    # JdbcTemplate 자체가 배치 콜을 실행할 때 로깅
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      item-service:
        url: http://localhost:8889
      user-service:
        url: http://localhost:8887
      payment-service:
        url: http://localhost:8886

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

feign:
  client:
    config:
      item-service:
        url: http://item-service:8082
      user-service:
        url: http://user-service:8080
      payment-service:
        url: http://payment-service:8079

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
  cloud:
    gateway:
      enabled: false

eureka:
  client:
    enabled: false

feign:
  client:
    config:
      item-service:
        url: http://localhost:8889
      user-service:
        url: http://localhost:8887
      payment-service:
        url: http://localhost:8886